# -*- coding: utf-8 -*-
"""SENTIMENTalci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQ-F2PHiHayvvhGoIX5BNVtpreq0QJku
"""

import urllib.request as ur
from bs4 import BeautifulSoup as bs
import re

linkovi=[]

for i in range(1,35):
  stranica=ur.urlopen(f"https://www.najboljeknjige.com/recenzije?stranica={i}")
  soup=bs(stranica)
  el_a=soup.body.findAll("a")
  l_href=re.findall(r"/recenzije/[a-z|-]+",str(el_a))
  for i in set(l_href):
    #print(i)
    linkovi.append(i)

l_p=[]

for recenzija in linkovi:
  stranica=ur.urlopen(f"https://www.najboljeknjige.com{recenzija}")
  soup=bs(stranica)
  el_p=soup.body.findAll("p")
  for i in el_p:
    l_p.append(i)

for i in l_p:
  print(i)

l_p_bkp=[]
for i in l_p:
  l_p_bkp.append(i)
l_p=[]
for i in l_p_bkp:
  l_p.append(re.sub(r"</?.+>","",str(i)))

for i in l_p:
  print(i)

with open("tekst.txt", "w", encoding="utf8") as dat:
  for i in l_p:
    dat.write(i)